--- #YAML:1.0
name:               Apache-SdnFw
version:            0.91
abstract:           Framework to build systems using perl, template toolkit and postgresql.
author:
    - Chris Sutton <chris@smalldognet.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Crypt::Blowfish:      0
    Crypt::CBC:           0
    Data::Dumper:         0
    Date::Format:         0
    DBD::Pg:              0
    DBI:                  0
    Digest::MD5:          0
    Google::SAML::Response:  0
    Lingua::EN::Numbers:  0
    LWP::UserAgent:       0
    MIME::Base64:         0
    MIME::QuotedPrint:    0
    Net::FTP:             0
    Net::SMTP::SSL:       0
    Template:             0
    Time::CTime:          0
    XML::Dumper:          0
    XML::Simple:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
